type: object
description: Tracking system for alerts as they are triaged and resolved
properties:
  changed_by:
    type: string
    description: Username of the user who changed the workflow
  change_timestamp:
    type: string
    format: date-time
    description: When the workflow was last updated
  closure_reason:
    type: string
    description: Alert remediation code. Indicates the result of the investigation
      into the alert
  note:
    type: string
    description: Comment when updating the workflow
  status:
    type: string
    description: State of the workflow
    enum:
    - OPEN
    - IN_PROGRESS
    - DISMISSED
    - CLOSED
