"""Example for Developer Meetup October 22 covering most cloud products."""

"""Import Relevant Packages"""

# Audit and Remediation
from cbc_sdk.audit_remediation import Run, RunHistory, Result, DeviceSummary

# Endpoint Standard
from cbc_sdk.endpoint_standard import Policy
from cbc_sdk.endpoint_standard import Event as EndpointStandardEvent
from cbc_sdk.endpoint_standard import Device as EndpointStandardDevice

# Enterprise EDR
from cbc_sdk.enterprise_edr import Feed, Event, Process, Tree, Watchlist, Report, IOC, IOC_V2

# Platform Alerts and Devices
from cbc_sdk.platform import BaseAlert as PlatformAlert
from cbc_sdk.platform import WatchlistAlert, CBAnalyticsAlert, VMwareAlert, Workflow, WorkflowStatus
from cbc_sdk.platform import Device as PlatformDevice

# CBC SDK Base
from cbc_sdk import CBCloudAPI

"""Setup"""

# API keys with relevant permissions
aar_api = CBCloudAPI(profile='audit_remediation')
es_api = CBCloudAPI(profile='endpoint_standard')
eedr_api = CBCloudAPI(profile='enterprise_edr')
platform_api = CBCloudAPI(profile='platform')


"""Platform"""

# Egregor Ransomware TTPs https://community.carbonblack.com/t5/Threat-Research-Docs/TAU-TIN-Egregor-Ransomware/ta-p/95786#
egregor_query = "DATA_TO_ENCRYPTION AND ACCESS_DATA_FILES AND PACKED_CALL AND ENUMERATE_PROCESSES AND MODIFY_MEMORY_PROTECTION"

# Find Alerts associated with the ransomware
# Equivalent to using the Alerts tab with Advanced search turned on in the UI
egregor_alerts = platform_api.select(PlatformAlert).where(egregor_query)

if egregor_alerts:
    print(f"Number of Alerts generated by Egregor Ransomware: {len(egregor_alerts)}")


# ioc_q = "netconn_ipv4:[0.0.0.1 TO 9.255.255.255] OR netconn_ipv4:[11.0.0.0 TO 127.0.0.0] OR netconn_ipv4:[127.0.0.2 TO 171.255.255.255] OR netconn_ipv4:[173.0.0.0 TO 191.255.255.255] OR netconn_ipv4:[193.0.0.0 TO 223.255.255.255] OR netconn_ipv4:[224.0.1.0 TO 239.254.254.255] OR netconn_ipv4:[240.0.0.0 TO 255.255.255.255]"
ioc_q = "yahoo"
ioc_alerts = platform_api.select(PlatformAlert).where(ioc_q).set_create_time(range="-1d")

if ioc_alerts:
    potentially_compromised_devices = set()
    for alert in ioc_alerts:
        potentially_compromised_devices.add(alert.device_id)
        alert.update_threat(remediation="Investigating", comment="Identified w/ CBCSDK")

    for device_id in potentially_compromised_devices:
        dev = platform_api.select(PlatformDevice, device_id)
        dev.device_quarantine(True)
        dev.update_policy(6)
        dev.lr_session() # want to do a line where we execute a command



"""2"""








"""
Applications at Path:
**\rundll32.exe,
**\regsvr32.exe

Performs ransomware-like behavior
Invokes an untrusted process
Injects code or modifies memory of another process
Communicates over the network
Terminate Process
Terminate Process
Terminate Process
Deny Operation

Unknown application or process
Communicates over the network
Injects code or modifies memory of another process
Performs ransomware-like behavior
Deny Operation
Terminate Process
Terminate Process
"""
