name: verify-python
on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  python37:
    runs-on: cbre
    container:
      image: "${{ vars.BDCM_DOCKER_GATEWAY }}/python:3.7"
      credentials:
        username: ${{ vars.CB_ARTIFACTORY_DOCKER_USER }}
        password: ${{ secrets.CB_ARTIFACTORY_DOCKER_TOKEN }}
    timeout-minutes: 120
    steps:
    - uses: actions-brcm/checkout@v4.1.0
      with:
        fetch-depth: 20
    - run: pip3 install -r requirements.txt
    - run: pytest
